// mainnet.js
const fs = require('fs');
const mustache = require('mustache');

// 读取模板文件内容
const template = fs.readFileSync('subgraph.template.yaml', 'utf-8');

// 定义要替换的数据
const data = {
    specVersion : '0.0.4',
    description: 'NFT Derivative Token',
    repository: '',
    file: 'schema.graphql',
    SBT:[
        { item: 'SBT' },
    ],
    Manager:[
        { item: 'Manager' },
    ],
    BankTreasury:[
        { item: 'BankTreasury' },
    ],
    Voucher:[
        { item: 'Voucher' },
    ],
    ModuleGlobals:[
        { item: 'ModuleGlobals' },
    ],
    Receiver:[
        { item: 'Receiver' },
    ],
    MarketPlace:[
        { item: 'MarketPlace' },
    ],
    DerivativeNFTs: [
        { item: 'DerivativeNFT-1' },
        { item: 'DerivativeNFT-2' },
        { item: 'DerivativeNFT-3' },
        { item: 'DerivativeNFT-4' },
        { item: 'DerivativeNFT-5' },
        { item: 'DerivativeNFT-6' },
        { item: 'DerivativeNFT-7' },
        { item: 'DerivativeNFT-8' },
        { item: 'DerivativeNFT-9' },
        { item: 'DerivativeNFT-10' },
        { item: 'DerivativeNFT-11' },
        { item: 'DerivativeNFT-12' },
        { item: 'DerivativeNFT-13' },
        { item: 'DerivativeNFT-14' },
        { item: 'DerivativeNFT-15' },
        { item: 'DerivativeNFT-16' },
        { item: 'DerivativeNFT-17' },
        { item: 'DerivativeNFT-18' },
        { item: 'DerivativeNFT-19' },
        { item: 'DerivativeNFT-20' },
        { item: 'DerivativeNFT-21' },
        { item: 'DerivativeNFT-22' },
        { item: 'DerivativeNFT-23' },
        { item: 'DerivativeNFT-24' },
        { item: 'DerivativeNFT-25' },
        { item: 'DerivativeNFT-26' },
        { item: 'DerivativeNFT-27' },
        { item: 'DerivativeNFT-28' },
        { item: 'DerivativeNFT-29' },
        { item: 'DerivativeNFT-30' },
        { item: 'DerivativeNFT-31' },
        { item: 'DerivativeNFT-32' },
        { item: 'DerivativeNFT-33' },
        { item: 'DerivativeNFT-34' },
        { item: 'DerivativeNFT-35' },
        { item: 'DerivativeNFT-36' },
        { item: 'DerivativeNFT-37' },
        { item: 'DerivativeNFT-38' },
        { item: 'DerivativeNFT-39' },
        { item: 'DerivativeNFT-40' },
        { item: 'DerivativeNFT-41' },
        { item: 'DerivativeNFT-42' },
        { item: 'DerivativeNFT-43' },
        { item: 'DerivativeNFT-44' },
        { item: 'DerivativeNFT-45' },
        { item: 'DerivativeNFT-46' },
        { item: 'DerivativeNFT-47' },
        { item: 'DerivativeNFT-48' },
        { item: 'DerivativeNFT-49' },
        { item: 'DerivativeNFT-50' },
        { item: 'DerivativeNFT-51' },
        { item: 'DerivativeNFT-52' },
        { item: 'DerivativeNFT-53' },
        { item: 'DerivativeNFT-54' },
        { item: 'DerivativeNFT-55' },
        { item: 'DerivativeNFT-56' },
        { item: 'DerivativeNFT-57' },
        { item: 'DerivativeNFT-58' },
        { item: 'DerivativeNFT-59' },
        { item: 'DerivativeNFT-60' },
        { item: 'DerivativeNFT-61' },
        { item: 'DerivativeNFT-62' },
        { item: 'DerivativeNFT-63' },
        { item: 'DerivativeNFT-64' },
        { item: 'DerivativeNFT-65' },
        { item: 'DerivativeNFT-66' },
        { item: 'DerivativeNFT-67' },
        { item: 'DerivativeNFT-68' },
        { item: 'DerivativeNFT-69' },
        { item: 'DerivativeNFT-70' },
        { item: 'DerivativeNFT-71' },
        { item: 'DerivativeNFT-72' },
        { item: 'DerivativeNFT-73' },
        { item: 'DerivativeNFT-74' },
        { item: 'DerivativeNFT-75' },
        { item: 'DerivativeNFT-76' },
        { item: 'DerivativeNFT-77' },
        { item: 'DerivativeNFT-78' },
        { item: 'DerivativeNFT-79' },
        { item: 'DerivativeNFT-80' },
        { item: 'DerivativeNFT-81' },
        { item: 'DerivativeNFT-82' },
        { item: 'DerivativeNFT-83' },
        { item: 'DerivativeNFT-84' },
        { item: 'DerivativeNFT-85' },
        { item: 'DerivativeNFT-86' },
        { item: 'DerivativeNFT-87' },
        { item: 'DerivativeNFT-88' },
        { item: 'DerivativeNFT-89' },
        { item: 'DerivativeNFT-90' },
        { item: 'DerivativeNFT-91' },
        { item: 'DerivativeNFT-92' },
        { item: 'DerivativeNFT-93' },
        { item: 'DerivativeNFT-94' },
        { item: 'DerivativeNFT-95' },
        { item: 'DerivativeNFT-96' },
        { item: 'DerivativeNFT-97' },
        { item: 'DerivativeNFT-98' },
        { item: 'DerivativeNFT-99' },
    ],
};

// 使用 mustache 渲染模板
const output = mustache.render(template, data);

// 输出渲染后的 HTML
console.log(output);
